### ISSUE TITLE
Error 500 with example script (Caddy 0.10.6) (minimal centos 7 64-bit)

### ISSUE THREAD

**Issue by magikstm** [jung-kurt/caddy-cgi#4] opened 2017-08-13 22:43 UTC
I downloaded Caddy 0.10.6 with the cgi plugin. The server is a minimal centos 7 64-bit.

Caddy does work to server .html files.

My caddyfile is:
> ###.##.##.###:80 {
> cgi /test1.cgi /usr/local/cgi-bin/test1.cgi
> errors
> log
> }

(It's an IP and not a domain name for now.)

Caddy is started with:
> sudo /home/centos/caddy -conf /home/centos/caddyfile

The CGI script permissions are 777 to ensure it may not be the issue.

I don't get an error in errors.log. I do get a 500 error when browsing the page and it is logged in access.log.

I tried the example script here: https://github.com/jung-kurt/caddy-cgi
(I also tried 2 other test scripts)

Is there a way to debug the error?

Am I missing something for it to work?

Thanks.

**Comment by jung-kurt** [comment] 2017-08-14 00:11
> I don't get an error in errors.log. 

That's a clue. Errors that show up there occur when the script is successfully launched but some script error causes it to write something to stderr.

> I do get a 500 error when browsing the page and it is logged in access.log.

What happens when you run the script from a shell prompt? If the script runs properly (that is, writes the header or headers followed by a blank line followed by content), then the problem is likely one or more missing environment variables that are present at the command prompt but missing in Caddy.

**Comment by magikstm** [comment] 2017-08-14 01:55
I don't know why at the moment, but this script doesn't work on my server:
```
#!/bin/bash
printf "Content-type: text/plain\n\n"
printf "PATH_INFO    [%s]\n" $PATH_INFO
printf "QUERY_STRING [%s]\n" $QUERY_STRING
exit 0
```

Thanks for the suggestion on testing the scripts in a shell prompt. After I did this other scripts worked:
`sudo yum install perl perl-CGI`

(ref: https://serverfault.com/questions/752272/run-perl-cgi-scripts-on-centos-7-with-apache-httpd)

Such as this one:
```
#!/usr/bin/perl -w
print "Content-type: text/html\n\n"; # This is mandatory.
print "<h2>Hello world!</h2>";
```

I have some scripts that don't have the same behavior in Caddy vs Apache.
I get such errors which I don't have with Apache: 
`Use of uninitialized value $foo`

These scripts are complicated (about 800 lines) and use subroutines. Can scripts with subroutines work well? I'm investigating the issue at the moment. It may be because of undefined environment variables.

**Comment by jung-kurt** [comment] 2017-08-14 11:49
> I don't know why at the moment, but this script doesn't work on my server:

From the command prompt, try the command `/bin/bash --version`. If you get a response like "No such file or directory", the shebang line will need to be adjusted to identify where the bash shell is located.

> Thanks for the suggestion on testing the scripts in a shell prompt.

I'll add this to the documentation. Most CGI programs require some environment variables from the web server that are not present in the shell, but at least the program should launch correctly.

> I have some scripts that don't have the same behavior in Caddy vs Apache.

This sounds to me like Apache is running one version of perl and Caddy another.

> Can scripts with subroutines work well? 

Yes. However, it may be that the interpreter needs information on where to find those subroutines. For example, ruby needs to have the subdirective `pass_env HOME` in the Caddyfile's cgi block.

> It may be because of undefined environment variables.

That's what I think. It seems like the script requires a variable that is not found in the limited set of environment variables that Caddy provides. You can pass additional variables with the `env` and `pass_env` subdirectives in the Caddyfile.

**Comment by magikstm** [comment] 2017-08-15 02:21
I tested and both servers have the same version of Perl and CGI. Which are:
```
perl: 5.016003
CGI: 3.63
```

I checked environment variables and there doesn't seem to be something that may trigger the issue.

First lines giving errors are the last two here:
```
#  For those without CGI module
sub readParse() {
   my ($len, $meth, $type, $in);
   my %in;

   # Read three useful environment variables
   $type = $ENV{'CONTENT_TYPE'};
   $len  = $ENV{'CONTENT_LENGTH'};
```

I get errors like these:
```
Use of uninitialized value $type
Use of uninitialized value $len
```

It's as if the parser in caddy-cgi and httpd-cgi don't have exactly the same behavior when they read the script. I'm investigating the issue.

Is there a special parsing on subroutines?

I used this script to confirm environment variables both in Caddy and httpd:
```
#!/usr/bin/perl -w

print "Content-type: text/html\n\n";
print "<pre>\n";

foreach $key (sort keys(%ENV)) {
  print "$key = $ENV{$key}<p>";
}
print "</pre>\n";
```

**Comment by jung-kurt** [comment] 2017-08-15 11:37
> It's as if the parser in caddy-cgi and httpd-cgi don't have exactly the same behavior when they read the script. 

Neither Caddy nor Apache parse CGI scripts, not even the shebang line. All they do is pass the script to the system for program execution.

> $type = $ENV{'CONTENT_TYPE'};
> $len  = $ENV{'CONTENT_LENGTH'};

This is a real clue. These variables are empty for GET requests (as opposed to POST requests that usually send some content to the server). However, Caddy and Apache may do things differently here. The heavy lifting for CGI in Caddy is done by Go's standard library in [net/http/cgi](https://golang.org/src/net/http/cgi/host.go). It seems to me on first glance that the standard library passes CONTENT_TYPE and CONTENT_LENGTH only if the values are not empty. If Apache always passes them, then that could explain the different behavior you experience.

Type commenting those lines out in your script and replacing them with assignments to empty strings instead. If the script succeeds, I will look into making sure CONTENT_TYPE and CONTENT_LENGTH are always passed, even if empty, when Caddy executes a CGI script.

**Comment by magikstm** [comment] 2017-08-16 00:45
Thanks.

The call is a `GET` yes.

It does go further if I change these:
```
$type = $ENV{'CONTENT_TYPE'};
$len = $ENV{'CONTENT_LENGTH'};
```

To these:
```
$type = '';
$len  = 0;
```

This parameter seems to have a similar issue:
`REMOTE_USER`

If I set it in code to en empty string it passes. Otherwise I get `Use of uninitialized value $username` eventually.

I also explained the last error I had in my script, but I'm unsure if that one may be corrected.

I have that line that links to a file:
`$ERROR_LOG_FILE = "secure/error.log";`

It can't open my file currently even if it is as I have it in Apache. Which is:
`/SCRIPT_PATH/secure`

If I edit the line as such it works:
`$ERROR_LOG_FILE = "/SCRIPT_PATH/secure/error.log";`

The file is opened with this line:
`open (LOG, ">>$filename");` (which is the variable $ERROR_LOG_FILE)

It's as if it reads the path 'as-is' and it doesn't consider the script path.

I do run the script directly from it's path in Apache. Which may explain why it works.

Could it be that caddy-cgi would need an extra parameter to pass the relative path to the file so that it may be used by the script? Or could it be adjusted to do so in a manner that would remain compatible for other possibilities?

I would prefer using the script as-is if possible. I checked CGI environment variables and I don't think it may be set with one of them.

My references are:
1) http://www.cgi101.com/book/ch3/text.html
2) http://docs.roxen.com/roxen/5.1/system_developer_manual/languages/cgi_environment.xml

**Comment by magikstm** [comment] 2017-08-16 00:47
For my last error, I could possibly use something like this:
https://stackoverflow.com/questions/9516428/relative-file-paths-in-perl

But, I would prefer to keep the script as-is if that may be possible.

**Comment by jung-kurt** [comment] 2017-08-16 21:19
It looks to me like your perl script errors out if the CONTENT_TYPE and CONTENT_LENGTH are not set, even for GET request that have not data attached. However, the [CGI specification](https://tools.ietf.org/html/rfc3875) says

> The CONTENT_LENGTH variable contains the size of the message-body attached to the request, if any, in decimal number of octets.  If no data is attached, then NULL (or unset). ... The server MUST set this meta-variable if and only if the request is accompanied by a message-body entity. 

I suspect Apache sets these variables to empty strings (arguably NULL), whereas the Go standard library used by Caddy CGI leaves them unset. In the first case, your perl script succeeds; in the latter, it fails.

As much as you don't want to change your scripts, I think it is the appropriate course of action here. The alternative is to petition the Go authors to mimic Apache and set these variables to empty strings, something that requires a rather liberal reading of the spec.

**Comment by magikstm** [comment] 2017-08-16 22:46
Thanks.

This script handles billing with a 3rd-party and it is provided as-is by the company (any change would void support).

I'll look at my options.

**Comment by jung-kurt** [comment] 2017-08-17 03:00
I'll look at options, too. Maybe an emulate-Apache mode.

**Comment by magikstm** [comment] 2017-08-17 03:34
Possibly with a parameter?

That would be awesome. It may allow both go's behavior as well as apache's.

**Comment by jung-kurt** [comment] 2018-03-20 21:09
I addressed this with a more general solution. The subdirective `empty_env` can now be used (with [v1.6](f81f187ef45972984b615a3f9da5c9ad326cafe0)) to pass along empty values of the environment variables that some scripts may expect.

**Comment by jung-kurt** [comment] 2018-04-06 14:26
I'll close this issue. If the `empty_env` subdirective does not as expected, the issue can be reopened.

**Closed as completed by jung-kurt** 2018-04-06 14:26 UTC
